# Generated by Django 6.0.2 on 2026-02-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreport',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='overall_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='teacher_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
