# Generated by Django 6.0.2 on 2026-02-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0002_remove_progressreport_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='grade',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='overall_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='teacher_remarks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='term',
            field=models.CharField(default='', max_length=50),
        ),
    ]
